/*
  New Delhi Darbar — brand info & notices.
  Menu categories/items live in assets/data/menu.csv.
  Generated by the private Admin Panel — edit there, then re-export.
*/
window.NDD_CONFIG = {
  "brand": {
    "name": "New Delhi Darbar",
    "tagline": {
      "en": "Restaurant",
      "hi": "",
      "gu": ""
    },
    "since": {
      "en": "Serving Since 2001",
      "hi": "",
      "gu": ""
    },
    "specialty": {
      "en": "Chokha na Rotla & Chokha na Pudaa Specialists",
      "hi": "",
      "gu": ""
    },
    "meta": {
      "en": "Bulk Orders Welcome • Authentic Taste • Quality You Can Count On",
      "hi": "",
      "gu": ""
    },
    "phones": [
      "+91 75675 87816",
      "+91 97120 52249"
    ],
    "address": {
      "en": "Opp. Masjid, Nana Taiwad, Valsad. 396001",
      "hi": "",
      "gu": ""
    },
    "mapUrl": "https://maps.app.goo.gl/PcJ4x3PgARtX2wjEA",
    "stockNote": {
      "en": "Please note: Items are served subject to availability. Thank you for your understanding.",
      "hi": "कृपया ध्यान दें: उपलब्धता के अनुसार ही व्यंजन परोसे जाएंगे।",
      "gu": "કૃપા કરીને નોંધો: ઉપલબ્ધતા મુજબ જ વાનગીઓ પીરસવામાં આવશે."
    },
    "sourceNote": {
      "en": "All prices are in Indian Rupees. Taxes and service charges are not included unless stated otherwise.",
      "hi": "सभी कीमतें भारतीय रुपये में हैं। जब तक अलग से न बताया जाए, इनमें टैक्स और सर्विस चार्ज शामिल नहीं हैं।",
      "gu": "બધી કિંમતો ભારતીય રૂપિયામાં છે. જ્યાં સુધી અલગથી જણાવવામાં ન આવે ત્યાં સુધી તેમાં ટેક્સ અને સર્વિસ ચાર્જ સામેલ નથી."
    },
    "pricingDisclaimer": {
      "en": "<i> Prices are in Indian Rupees (₹). Applicable taxes and service charges are additional unless otherwise stated. </i>",
      "hi": "कीमतें भारतीय रुपये (₹) में हैं। लागू कर और सेवा शुल्क अतिरिक्त हैं जब तक कि अन्यथा न कहा गया हो।",
      "gu": "કિંમતો ભારતીય રૂપિયા (₹) માં છે. લાગુ કર અને સેવા શુલ્ક વધારાના છે સિવાય કે અન્યથા જણાવ્યું હોય."
    }
  },
  "notices": [
    {
      "title": {
        "en": "Fresh preparation",
        "hi": "ताज़ा तैयारी",
        "gu": "તાજી તૈયારી"
      },
      "html": {
        "en": "<strong>Chicken, Mutton &amp; Fish</strong> are prepared fresh as per your order and preference. Quantities and preparation can be customized according to your requirements. Prices may vary based on the quality, quantity, and preparation of the food.",
        "hi": "<strong>चिकन, मटन और मछली</strong> आपके ऑर्डर और पसंद के अनुसार ताज़ा तैयार किए जाते हैं। मात्रा और तैयारी आपकी आवश्यकता के अनुसार बदली जा सकती है। भोजन की गुणवत्ता, मात्रा और तैयारी के अनुसार कीमत अलग हो सकती है।",
        "gu": "<strong>ચિકન, મટન અને ફિશ</strong> તમારા ઓર્ડર અને પસંદગી મુજબ તાજા તૈયાર કરવામાં આવે છે. માત્રા અને તૈયારી તમારી જરૂરિયાત મુજબ કસ્ટમાઇઝ કરી શકાય છે. ખોરાકની ગુણવત્તા, માત્રા અને તૈયારી મુજબ કિંમત અલગ હોઈ શકે છે."
      },
      "bulkPricing": {
        "en": "",
        "hi": "",
        "gu": ""
      },
      "bulkList": []
    },
    {
      "title": {
        "en": "Special Note",
        "hi": "विशेष सूचना",
        "gu": "ખાસ નોંધ"
      },
      "html": {
        "en": "We also accept <strong>bulk quantity orders</strong> for:",
        "hi": "हम <strong>बड़ी मात्रा के ऑर्डर</strong> भी स्वीकार करते हैं:",
        "gu": "અમે <strong>મોટી માત્રાના ઓર્ડર</strong> પણ સ્વીકારીએ છીએ:"
      },
      "bulkList": [
        {
          "en": "Plain Roti",
          "hi": "सादी रोटी",
          "gu": "ઘઉં ની રોટલી"
        },
        {
          "en": "Chokha na Rotla",
          "hi": "चावल के रोटला",
          "gu": "ચોખા ના રોટલા"
        },
        {
          "en": "Chokha na Pudaa",
          "hi": "चावल के पुड़ा",
          "gu": "ચોખા ના પુડા"
        }
      ],
      "bulkPricing": {
        "en": "<strong>Special bulk-order pricing:</strong> The price remains <strong>the same even for large quantities</strong>. Please place your order in advance for bulk quantities.",
        "hi": "<strong>विशेष बल्क-ऑर्डर मूल्य:</strong> बड़ी मात्रा में भी <strong>कीमत समान रहती है</strong>। बड़ी मात्रा के लिए कृपया पहले से ऑर्डर करें।",
        "gu": "<strong>ખાસ બલ્ક-ઓર્ડર કિંમત:</strong> મોટી માત્રા માટે પણ <strong>કિંમત સમાન રહેશે</strong>. મોટી માત્રા માટે કૃપા કરીને અગાઉથી ઓર્ડર આપો."
      }
    }
  ],
  "lastUpdated": "2026-08-16T17:44:31.642Z"
};
